// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewUser struct {
	FirstName   string   `json:"first_name"`
	LastName    string   `json:"last_name"`
	PhoneNumber string   `json:"phone_number"`
	Long        *float64 `json:"long"`
	Lat         *float64 `json:"lat"`
}

type User struct {
	ID          string   `json:"id"`
	CreatedAt   *string  `json:"created_at"`
	UpdatedAt   *string  `json:"updated_at"`
	FirstName   *string  `json:"first_name"`
	LastName    *string  `json:"last_name"`
	PhoneNumber string   `json:"phone_number"`
	Long        *float64 `json:"long"`
	Lat         *float64 `json:"lat"`
	UserType    *int     `json:"user_type"`
}
