// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type LoginParams struct {
	PhoneNumber   string `json:"phone_number"`
	OtpCode       string `json:"otp_code"`
	PasscodeToken string `json:"passcode_token"`
}

type LoginResponse struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refresh_token"`
}

type NewUser struct {
	FirstName   string   `json:"first_name"`
	LastName    string   `json:"last_name"`
	PhoneNumber string   `json:"phone_number"`
	Long        *float64 `json:"long"`
	Lat         *float64 `json:"lat"`
}

type UpdateResponse struct {
	ID string `json:"id"`
}

type UpdateUser struct {
	FirstName *string  `json:"first_name"`
	LastName  *string  `json:"last_name"`
	Long      *float64 `json:"long"`
	Lat       *float64 `json:"lat"`
}

type User struct {
	ID          string   `json:"id"`
	CreatedAt   *string  `json:"created_at"`
	UpdatedAt   *string  `json:"updated_at"`
	FirstName   *string  `json:"first_name"`
	LastName    *string  `json:"last_name"`
	PhoneNumber string   `json:"phone_number"`
	Long        *float64 `json:"long"`
	Lat         *float64 `json:"lat"`
	UserType    *int     `json:"user_type"`
}
