// Code generated by sqlc. DO NOT EDIT.
// source: status.sql

package sqlc

import (
	"context"
)

const getStatusByName = `-- name: GetStatusByName :one
SELECT id, name FROM status WHERE name = $1
`

func (q *Queries) GetStatusByName(ctx context.Context, name string) (Status, error) {
	row := q.db.QueryRowContext(ctx, getStatusByName, name)
	var i Status
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
